#
# This file contains configuration variables for drivers.
# It was generated by genhdrs.pl. Do not modify it.
#
package Driverhdrs;

$LAB = "datalab";
$SERVER_NAME = "10.12.13.30";
$SERVER_PORT = 8083;
$COURSE_NAME = "csapp";
$AUTOGRADE_TIMEOUT = 0;
1;
